## Numpy Basic

## Consider the below code to answer further question:
## import numpy as np
## list_ = ["1","2","3","4","5"]
## arry_list = np.arry(object = list_)

## Q.1  Is there any difference in the data type of variables list_and arry_list? If there is then write a code to print the data types of both the variables.

## Q.2 Write a code to print the data type of each and every element of both the variables list_and arra_list.

In [1]:
import numpy as np

In [2]:
list_data=[1,2,3,2.3,"souma","False",2+7j,99]
array_list=np.array([1,2,3,4,5,6])

In [3]:
def Data_type(variable):
    for i in variable:
        print(f"{i}:{type(i)}")

In [4]:
Data_type(list_data)

1:<class 'int'>
2:<class 'int'>
3:<class 'int'>
2.3:<class 'float'>
souma:<class 'str'>
False:<class 'str'>
(2+7j):<class 'complex'>
99:<class 'int'>


In [5]:
Data_type(array_list)

1:<class 'numpy.int64'>
2:<class 'numpy.int64'>
3:<class 'numpy.int64'>
4:<class 'numpy.int64'>
5:<class 'numpy.int64'>
6:<class 'numpy.int64'>


## Q.3 Considering the following changes in the variable, arry_list:
## array_list = np.array(object = list_, dtype = int)
    
## will there be any difference in the data type of the elements present in both the variables, list_and arra_list? If so then print the data types of each and every element present in both the variables, list_ and arra_list.

## Consider the below code to answer further questions:
## import numpy as np
## num_list = [[1,2,3],[4,5,6]]
    
## num_array = np.array(object = num_list)

In [6]:
array_list = np.array(object = array_list, dtype = int)

In [7]:
array_list

array([1, 2, 3, 4, 5, 6])

In [8]:
import numpy as np
num_list = [[1,2,3],[4,5,6]]
num_array = np.array(object = num_list)

In [9]:
num_array

array([[1, 2, 3],
       [4, 5, 6]])

In [10]:
def Data_type(variable):
    for i in variable:
        print(f"{i}:{type(i)}")

In [11]:
Data_type(num_array)

[1 2 3]:<class 'numpy.ndarray'>
[4 5 6]:<class 'numpy.ndarray'>


## Q.4 Write a code to find the following characteristics of variable, num_array:
## (i)  shape
## (ii) size

## i) Shape

In [12]:
arr1=np.array([[1,2,3,4],[1,2,11,22],[22,33,44,22]])

In [13]:
arr1.shape

(3, 4)

# ii) size

In [14]:
arr1=np.array([[1,2,3,4],[1,2,11,22],[22,33,44,22]])

In [15]:
arr1.size

12

## Q.5 Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array creation function.
## [Hint: The size of the array will be 9 and the shape will be(3,3)]

In [16]:
arr2=np.zeros((3,3))

In [17]:
arr2

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [18]:
arr2.shape

(3, 3)

In [19]:
arr2.size

9

## Q.6 Create an identity matrix of shape(5,5) using numpy functions?
## [Hint: An identity matrix is amatrix containing 1 diagonally and other elements will be 0.]

In [20]:
arr3=np.eye(5)

In [21]:
arr3

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])